Allowing Import Image from Gallery on Android
vicajilau/cunning_document_scanner pull request #51
Opened 2024-03-04 14:18 UTC by vicajilau

2024-03-04 15:45 UTC, CodeRedDev reviewed
Functional part looks good 👍 

README has some errors.

1. Part of the description of `noOfPages` slipped under the description for `isGalleryImportAllowed`
2. `noOfPages` also only works on Android. The parameter is never used in the iOS implementation.

2024-03-04 22:15 UTC, CodeRedDev requested changes
I would like to suggest a version that increases the readability:

## How to use ?

The easiest way to get a list of images is:

```
    final imagesPath = await CunningDocumentScanner.getPictures()
```

#### Android Specific

```kotlin
final imagesPath = await CunningDocumentScanner.getPictures(
    noOfPages: 1, // Limit the number of pages to 1
    isGalleryImportAllowed, // Allow the user to also pick an image from his gallery
)
```

2024-03-05 08:28 UTC, CodeRedDev approved these changes
Nice 👍

2024-03-05 08:37 UTC, jachzen approved these changes

2024-03-05 08:37 UTC, merged